packages:
  common: !include satellite1.common.yaml

# Dashboard import enables automatic updates from GitHub
dashboard_import:
  package_import_url: github://remcom/Satellite1-ESPHome/config/satellite1-dashboard.yaml@main
  import_full_config: false
