substitutions:
  ota_manifest: satellite1.ld2410

packages:
  base_image: !include satellite1.yaml
  mmwave_ld2410: !include common/mmwave_ld2410.yaml

esphome:
  name: ${node_name}
  project:
    name: ${company_name}.${project_name}
    version: ${esp32_fw_version}+ld2410

# Dashboard import enables automatic updates from GitHub
dashboard_import:
  package_import_url: github://remcom/Satellite1-ESPHome/config/satellite1-dashboard.yaml@main
  import_full_config: false
